#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if ! head -1 "$1" | grep -qE "^(feat|design|fix|ci|cd|chore|comment|docs|test|style|refactor|perf|build|revert|rename|remove)(\(.+?\))?: .{1,}$"; then
  echo "Aborting commit. Your commit message is invalid." >&2
  exit 1
fi

if ! head -1 "$1" | grep -qE "^.{1,500}$"; then
  echo "Aborting commit. Your commit message is too long." >&2
  exit 1
fi
