stages:
  - deploy

deploy:
  stage: deploy
  only:
    - tags
  tags:
    - docker
  before_script:
    - echo [INFO] Current version - $CI_COMMIT_TAG
    - echo [INFO] Checking Docker and Docker Compose..
    - docker --version
    - docker-compose --version

    - echo [INFO] Setting up environment variables...
    - echo "EMAILJS_SERVICE_ID=$EMAILJS_SERVICE_ID" >> client/.env.local
    - cat client/.env.local
    # - echo "$CLIENT_ENV_FILE" > "client/.env.local"

  script:
    - echo [INFO] Deployment started.

    - echo "Cleaning up previous containers and networks..."
    - docker-compose -f docker-compose.prod.yml down

    - echo "Pruning unused volumes..."
    - docker volume prune -f

    - echo "Starting new containers..."
    - docker-compose -f docker-compose.prod.yml up --build -d

    - echo "Removing unused images..."
    - docker rmi $(docker images -f dangling=true -q)

  after_script:
    - echo [INFO] Deployment completed.
