workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main"
      when: never
    - when: always

stages:
  - build
  - deploy

build-image:
  only:
    - main
  stage: build
  tags:
    - docker
  script:
    - echo "Building the docker image.."
    - echo "Tagging the docker image.."

push-image:
  only:
    - main
  stage: build
  tags:
    - docker
  needs:
    - build-image
  script:
    - echo "Logging into docker registry..."
    - echo "Pushing docker image to registry..."

deploy-image:
  only:
    - main
  stage: deploy
  tags:
    - docker
  script:
    - echo "Deploying docker image..."
