workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main"
      when: never
    - when: always

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - main
  tags:
    - docker
  before_script:
    - echo [INFO] Checking Docker and Docker Compose...
    - docker --version
    - docker-compose --version
    - echo [INFO] Setting environment files...
    # - echo "$ENV_FILE_CLIENT" > ./client/.env.local
    - echo "$ENV_FILE_SERVER" > ./server/.env
    - echo "$ENV_FILE_SERVER"

  script:
    - echo [INFO] Deployment started.

    # - echo "Cleaning up previous containers and networks..."
    # - docker-compose -f docker-compose.prod.yml down

    # - echo "Pruning unused volumes..."
    # - docker volume prune -f

    # - echo "Starting new containers..."
    # - docker-compose -f docker-compose.prod.yml up --build -d

    # - echo "Removing unused images..."
    # - docker rmi $(docker images -f dangling=true -q)

  after_script:
    - echo [INFO] Deployment completed.
