workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main"
      when: never
    - when: always

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - main
  tags:
    - docker
  before_script:
    - echo [INFO] Checking Docker and Docker Compose...
    - docker version
    - docker-compose version

  script:
    - echo [INFO] Starting deployment on AWS EC2 instance with Docker socket
    # - docker-compose -f docker-compose.prod.yml down
    # - docker-compose -f docker-compose.prod.yml up -d --build
    # - docker rmi $(docker images -f dangling=true -q) # dangling 이미지 정리
