workflow:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
      when: always
    - when: never

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - tags
  tags:
    - docker
  before_script:
    - echo [INFO] Checking Docker and Docker Compose...
    - docker --version
    - docker-compose --version
    - echo "The current tag is - $CI_COMMIT_TAG"

  script:
    - echo [INFO] Deployment started.

    # - echo "Cleaning up previous containers and networks..."
    # - docker-compose -f docker-compose.prod.yml down

    # - echo "Pruning unused volumes..."
    # - docker volume prune -f

    # - echo "Starting new containers..."
    # - docker-compose -f docker-compose.prod.yml up --build -d

    # - echo "Removing unused images..."
    # - docker rmi $(docker images -f dangling=true -q)

  after_script:
    - echo [INFO] Deployment completed.
