name: uyblog

services:
  server-dev:
    container_name: server-dev
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 5002:5000
    env_file:
      - ./server/.env
    volumes: # dev
      - ./server/src:/app/src
    depends_on:
      - mongodb
    networks:
      - blog

  client-dev:
    container_name: client-dev
    restart: unless-stopped
    build:
      context: ./client
      target: dev
      dockerfile: Dockerfile.dev
    command: yarn dev
    ports:
      - 3002:3000
    environment:
      - NODE_ENV=development # dev
      - WATCHPACK_POLLING=true # for window user # dev
    env_file:
      - ./client/.env.local
    volumes: # dev
      - ./client/src:/app/src
      # - /app/node_modules
      # - /app/.next
    depends_on:
      - server-dev
    networks:
      - blog

  mongodb:
    image: mongo:7.0.14
    container_name: mongodb-dev
    restart: always
    ports:
      - 27019:27017
    volumes:
      - mongodb:/data/db
    networks:
      - blog

  nginx:
    container_name: nginx-dev
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 8082:80
    depends_on:
      - server-dev
      - client-dev
    networks:
      - blog

volumes:
  mongodb:

networks:
  blog:
