name: uyblog

services:
  server-prod:
    container_name: server-prod
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    networks:
      - blog

  client-prod:
    container_name: client-prod
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    depends_on:
      - server-prod
    networks:
      - blog

  mongodb:
    image: mongo:7.0.14
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - blog

  nginx:
    image: nginx:1.27.1-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server-prod
      - client-prod
    networks:
      - blog

volumes:
  mongodb:

networks:
  blog:
