name: uyblog

services:
  server-dev:
    container_name: server-dev
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    env_file:
      - ./server/.env
    volumes: # dev
      - ./server/src:/app/src
    depends_on:
      - mongodb
    networks:
      - blog

  client-dev:
    container_name: client-dev
    restart: unless-stopped
    build:
      context: ./client
      target: dev
      dockerfile: Dockerfile.dev
    command: yarn dev
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development # dev
      - WATCHPACK_POLLING=true # for window user # dev
    env_file:
      - ./client/.env.local
    volumes: # dev
      - ./client/src:/app/src
      # - /app/node_modules
      # - /app/.next
    depends_on:
      - server-dev
    networks:
      - blog

  client-nginx-dev:
    container_name: client-nginx-dev
    restart: unless-stopped
    build:
      context: ./client/nginx
      dockerfile: Dockerfile.nginx.dev
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development # dev
      - WATCHPACK_POLLING=true # for window user # dev
    volumes: # dev
      - ./client/nginx/client-nginx-dev.conf:/etc/nginx/conf.d/client-nginx-dev.conf
    depends_on:
      - server-dev
      - client-dev
    networks:
      - blog

  mongodb:
    image: mongo:7.0.14
    container_name: mongodb-dev
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - blog

  nginx:
    image: nginx:1.27.1-alpine
    container_name: nginx-dev
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf # dev
    depends_on:
      - server-dev
      - client-dev
      - client-nginx-dev
    networks:
      - blog

volumes:
  mongodb:

networks:
  blog:
